### ISSUE TITLE
printp raises error when value is NA

### ISSUE THREAD

**Issue by dhagmann** [crsh/papaja#278]
The convenience wrapper for printnum to print p-values gives the following error when an NA value is an argument (or part of a vector):

`papaja::printp(NA, na_string = '')`
> Error in validate(x, check_class = "numeric", check_range = c(0, 1)) : 
  The parameter 'x' is NA.

Reading the function, I think the desired behavior is that it instead prints the NA string (in this case an empty string). It also seems the bug is in the first `validate` function call. Seems like it would be straight-forward to fix, but I'm afraid I can't figure out how to -- or I'd have included a pull request.

**Comment by crsh** [comment]
Hi David, thanks for alerting me to this. Should now be fixed on the development branch (`remotes::install_github("crsh/papaja@devel")`)

**Comment by angelinetsui** [comment]
Hello @crsh , I have the same problem in knitting my Rmd. I tried to fix this by (remotes::install_github("crsh/papaja@devel")) but I got another message, see below:

Skipping install of 'papaja' from a github remote, the SHA1 (b7d1c8c4) has not changed since last install.
  Use `force = TRUE` to force installation

After all, I still can't knit my Rmd, please advise!
