### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by jamesrrae** [crsh/papaja#292]
It seems like fourth and fifth level headers aren't following apa 6 formatting. In these instances, the body of the paragraph is supposed to begin immediately after the header (see here: https://blog.apastyle.org/apastyle/2011/04/how-to-use-five-levels-of-heading-in-an-apa-style-paper.html). For example, this is what the text should look like:

"_Measures._ This describes the measures."

Instead, I'm getting this output:

"_Measures._ 

This describes the measures."

I've attached an example .Rmd file to document the behavior.
[test.zip](https://github.com/crsh/papaja/files/3290248/test.zip)

**Comment by crsh** [comment]
Thanks, I was alerted to this with respect to [fourth level headers](https://github.com/crsh/papaja/issues/284) before but I haven't had time to look into this more closely. I do know that this is indeed an issue with `papaja` rather than the underlying `apa6` class. I'll try to address this as soon as possible.

**Comment by jamesrrae** [comment]
Great. Is there a work around I might be able to use in the meantime? I'd like to submit a PDF for review and ensuring the formatting is correct is one of the last things on my to do list. Any tips on how I can find a short term fix would be appreciated.

**Comment by crsh** [comment]
Okay, I've finally found some time to look into this. This is caused by a redefinition of these headings done in the `pandoc` LaTeX template. This has been changed in version [2.7.2](https://github.com/jgm/pandoc/blob/master/changelog.md#pandoc-272-2019-04-05) (see https://github.com/jgm/pandoc/issues/5365) but since it's not clear when this will take effect in `rmarkdown` I've added the original `apa6` definitions of `\paragraph` and `\subparagraph` to the preamble, which should fix the issue.

Try the latest development version to see if that fixes the issue for you (`devtools::install_github("crsh/papaja@devel")`).

**Comment by jstevens5** [comment]
I'm still having this problem using `papaja` version 0.1.0.9997, `rmarkdown version 2.3`, and `pandoc` version 2.10`.

**Comment by crsh** [comment]
Could you post the CLI `pandoc` call from your Markdown pane in RStudio?

**Comment by jstevens5** [comment]
Sure:
`/usr/bin/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash+raw_attribute --output test.tex --self-contained --highlight-style tango --pdf-engine pdflatex --include-in-header /home/jstevens/R/x86_64-pc-linux-gnu-library/4.0/papaja/rmarkdown/templates/apa6/resources/apa6_header_includes.tex --variable graphics --lua-filter /usr/lib/R/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/lib/R/site-library/rmarkdown/rmd/lua/latex-div.lua --wrap preserve --csl /home/jstevens/R/x86_64-pc-linux-gnu-library/4.0/papaja/rmd/apa6.csl --filter /usr/bin/pandoc-citeproc --lua-filter /home/jstevens/R/x86_64-pc-linux-gnu-library/4.0/rmdfiltr/replace_ampersands.lua --lua-filter /home/jstevens/R/x86_64-pc-linux-gnu-library/4.0/rmdfiltr/wordcount.lua --lua-filter /home/jstevens/R/x86_64-pc-linux-gnu-library/4.0/papaja/lua/parse_metadata.lua --variable 'classoption:man' --variable 'lang:en-EN' --variable 'subparagraph:yes' --variable 'block-headings:no' --include-in-header /tmp/RtmpTwONDA/includes_25bc4f412bf8.tex `

**Comment by crsh** [comment]
@jstevens5, I was able to confirm that the bug was back and added back in the original `apa6` definitions of `\paragraph` and `\subparagraph` to the preamble, which should fix the issue.

**Comment by jvcasillas** [comment]
I'm running the updated devl version of papaja on R 4.0.3 and I noticed today that headers of all levels include numbers. I don't recall this being the default behavior before and I'm pretty sure it isn't APA standards, but I am not up to speed on the newest changes. Is this possibly also a pandoc issue?

<img width="1118" alt="Screen Shot 2020-10-19 at 16 24 37" src="https://user-images.githubusercontent.com/1747068/96507957-e6cab180-1227-11eb-92fd-7d9b73c2f05c.png">

**Comment by crsh** [comment]
Hi Joseph, could you open a separate issue for this?

**Comment by jvcasillas** [comment]
> Hi Joseph, could you open a separate issue for this?

Of course. Reported here https://github.com/crsh/papaja/issues/422

**Comment by crsh** [comment]
@mariusbarth Could you try to verify that this issue is resolved?

**Comment by mariusbarth** [comment]
seems to work:

![Bildschirmfoto von 2020-11-23 16-27-04](https://user-images.githubusercontent.com/9460245/99980823-f69a6000-2da8-11eb-97e1-a040ac04ecc4.png)

**Comment by ericpgreen** [comment]
@mariusbarth I'm using the same version of papaja as you, but fourth and fifth level headings are not working as expected for me. Did you update something else, maybe the apa template?
